name: Dispatch Downstream Update Samples Event

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
    - name: Dispatch event
      uses: actions/github-script@v6
      with: 
        github-token: ${{secrets.OKTA_433527}}
        script: |
          github.rest.repos.createDispatchEvent({
            owner: context.repo.owner,
            repo: 'samples-js-react',
            event_type: 'update-samples',
            client_payload: { context }
          });
