name: Dispatch Downstream Update Samples Event

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Dispatch event
      uses: actions/github-script@v6
      with: 
        github-token: ${{secrets.OKTA_433527}}
        script: |
          const stdout = exec.exec(`npm info ${module} dist-tags --json`, { silent: true });
          const latestPublishedVersion = JSON.parse(stdout).latest;
          console.log(latestPublishedVersion);
          github.rest.repos.createDispatchEvent({
            owner: context.repo.owner,
            repo: 'samples-js-react',
            event_type: 'update-samples',
            client_payload: { context }
          });
